services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
    App\Applications\IPs\Listener\VisitListener:
        tags: [{ name: kernel.event_listener, event: kernel.request }]
