security:
    encoders:
        App\Applications\Doctrine\Entity\DoctrineUser: sha512
    providers:
        main:
            entity:
                class: App\Applications\Doctrine\Entity\DoctrineUser
                property: newEmail

    role_hierarchy:
        ROLE_USER:        ROLE_INCOMPLETE
        ROLE_ADMIN:       ROLE_USER

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern:   ^/
            anonymous: true
            provider:  main
            form_login:
                login_path: login
                check_path: login
                default_target_path: list_ip
                csrf_token_generator: security.csrf.token_manager

            logout:
                path:       logout
                target:     login
    access_denied_url: /fr/login
    access_control:
    - { path: ^/(en|fr)/show-ip, roles: ROLE_USER}
    - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY}
