App\Applications\Doctrine\Entity\DoctrineUser:
    type: entity
    table: User

    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 100
        email:
            type: string
            length: 150
            nullable: true
        newEmail:
            type: string
            length: 150
            nullable: true
        password:
            type: string
            length: 200
        token:
            type: string
            length: 255
            nullable: true
        salt:
            type: string
            length: 255
            nullable: true
        roles:
            type: array
